# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setupDatabase:
   runs-on: [ubuntu-latest]
   strategy:
     matrix:
       mongodb-version: [4.0, 4.2]
   steps:
     - uses: supercharge/mongodb-github-action@1.2.0
       name: Mongodb
       with:
         mongodb-version: ${{ matrix.mongodb-version }}
         mongodb-replica-set: testDb
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run test:cov
      env:
        CI: true
        MONGODB_URL: ${{secrets.MONGODB_URL}} 
        APP_SECREATE: ${{secrets.APP_SECREATE}} 
    needs: [setupDatabase]
